
package introsde.assignment3.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
//import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import introsde.assignment3.soap.entities.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://soap.assignment3.introsde/")
/*@XmlSeeAlso({
    ObjectFactory.class //Its somehow broken
})*/
public interface PersonWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorldAsString", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetHelloWorldAsString")
    @ResponseWrapper(localName = "getHelloWorldAsStringResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetHelloWorldAsStringResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/getHelloWorldAsStringRequest", output = "http://soap.assignment3.introsde/PersonWebService/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonList", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetPersonList")
    @ResponseWrapper(localName = "getPersonListResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetPersonListResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/getPersonListRequest", output = "http://soap.assignment3.introsde/PersonWebService/getPersonListResponse")
    public List<Person> getPersonList();

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetPersonResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/getPersonRequest", output = "http://soap.assignment3.introsde/PersonWebService/getPersonResponse")
    public Person getPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/updatePersonRequest", output = "http://soap.assignment3.introsde/PersonWebService/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreatePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/createPersonRequest", output = "http://soap.assignment3.introsde/PersonWebService/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.DeletePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/deletePersonRequest", output = "http://soap.assignment3.introsde/PersonWebService/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Activity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferences")
    @ResponseWrapper(localName = "readPersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/readPersonPreferencesRequest", output = "http://soap.assignment3.introsde/PersonWebService/readPersonPreferencesResponse")
    public List<Activity> readPersonPreferences(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Activity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPreferences")
    @ResponseWrapper(localName = "readPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/readPreferencesRequest", output = "http://soap.assignment3.introsde/PersonWebService/readPreferencesResponse")
    public List<Activity> readPreferences();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreference", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreference")
    @ResponseWrapper(localName = "readPersonPreferenceResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferenceResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/readPersonPreferenceRequest", output = "http://soap.assignment3.introsde/PersonWebService/readPersonPreferenceResponse")
    public Activity readPersonPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "savePersonPreference", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.SavePersonPreference")
    @ResponseWrapper(localName = "savePersonPreferenceResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.SavePersonPreferenceResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/savePersonPreferenceRequest", output = "http://soap.assignment3.introsde/PersonWebService/savePersonPreferenceResponse")
    public void savePersonPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Activity arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePersonPreference", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonPreference")
    @ResponseWrapper(localName = "updatePersonPreferenceResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonPreferenceResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/updatePersonPreferenceRequest", output = "http://soap.assignment3.introsde/PersonWebService/updatePersonPreferenceResponse")
    public Activity updatePersonPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Activity arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "evaluatePersonPreference", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.EvaluatePersonPreference")
    @ResponseWrapper(localName = "evaluatePersonPreferenceResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.EvaluatePersonPreferenceResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/evaluatePersonPreferenceRequest", output = "http://soap.assignment3.introsde/PersonWebService/evaluatePersonPreferenceResponse")
    public Activity evaluatePersonPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Activity arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Activity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBestPersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetBestPersonPreferences")
    @ResponseWrapper(localName = "getBestPersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetBestPersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonWebService/getBestPersonPreferencesRequest", output = "http://soap.assignment3.introsde/PersonWebService/getBestPersonPreferencesResponse")
    public List<Activity> getBestPersonPreferences(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
